FROM node:20-alpine AS builder

WORKDIR /app
COPY . .

ENV VITE_API=https://api.winterflowspace.com/

RUN npm install
RUN npm run build

FROM  arm64v8/nginx
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
