version: "3"
services: # Not the same as Kubernetes service
  flowception.co.uk: # Service name
    container_name: flowception.co.uk
    build: # Command
      context: . # This folder on the left
      dockerfile: ./Dockerfile
    image: flowception.co.uk
    hostname: flowception.co.uk
    ports:
      - "3000:3000"
