apiVersion: v2
name: flowception
description: The helm chart for flowception
type: application

version: 0.1.0
dependencies:
  - name: library
    version: ~1
    repository: "https://invisibug.github.io/kavanetes-helm/"

appVersion: "1.0.0"
